#problem 2

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms


def calculate_sum():
    sum = 2
    f_series2 = [1,2]
    for j in range (2,400000):
        f_series2.insert(j, (f_series2[j-1] + f_series2[j-2]))
        if (f_series2[j]%2==0):
            sum += f_series2[j]
        if f_series2[j] > 4000000:
            break
        j+=1

    return sum

print(calculate_sum())
